version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tp.items.topic:1:1"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9099,LOCAL://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9099,LOCAL://:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MAX_BLOCK_MS: 2000

  schemaregistry:
    image: confluentinc/cp-schema-registry:7.1.0
    restart: always
    depends_on:
      - zookeeper

    ports:
      - "8085:8085"

    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"